apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: avro-kafka-consumer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: avro-kafka-consumer
    kind: Deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75